# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate gperftools

Name:           rust-gperftools
Version:        0.2.0
Release:        %autorelease
Summary:        Bindings to google's gperftools

License:        BSD-2-Clause
URL:            https://crates.io/crates/gperftools
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  gperftools-devel

%global _description %{expand:
Bindings to google's gperftools.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       gperftools-devel

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+heap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+heap-devel %{_description}

This package contains library source intended for building other packages which
use the "heap" feature of the "%{crate}" crate.

%files       -n %{name}+heap-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
